# docker-compose.yaml
version: "2"
services:
  swagger_ui:
    environment:
      - SWAGGER_JSON=/swagger.json
    image:   "swaggerapi/swagger-ui"
    volumes: ["./shorturl-client/src/main/resources/swagger.json:/swagger.json"]
    restart: always
    ports:   ["80:8080"]