---
# tasks file for mongod
- name: mongod service user
  user:
    name: "{{ mongod_user }}"
    createhome: no
    shell: /bin/false
    group: "{{ mongod_user }}"
    state: present

- name: create systemd mongo service
  include_role:
    name: tumf.systemd-service
  vars:
    systemd_service_name: "mongodb"
    systemd_service_Service_ExecStart: "/usr/bin/mongod --config /etc/mongod.conf"
    systemd_service_Service_User: "{{ mongod_user }}"

- name: create mongod db path
  file:
    path: "{{ mongod_db_path }}"
    state: directory
    owner: "{{ mongod_user }}"
  with_items:
    - "{{ mongod_db_path }}"
    - "{{ mongod_system_log_path }}"

- name: mongod configuration
  template:
    src: templates/mongod.conf.j2
    dest: "/etc/mongod.conf"
  notify: restart mongod

- name: mongod started
  systemd:
    name: "mongodb"
    state: started
    enabled: yes

- name: copy rs init script
  template:
    src: templates/mongo-rs-init.js.j2
    dest: /tmp/mongo-rs-init.js
  when: mongo_master

- name: run rs init script
  shell: "mongo --port {{ mongod_port }} < /tmp/mongo-rs-init.js"
  when: mongo_master

- name: open firewall port for mongod
  command: firewall-cmd --zone=public --add-port="{{ item }}" --permanent
  with_items:
    - 27017/tcp
    - 27020/tcp
    - 27021/tcp
    - 27022/tcp
